# TODO: OS X & Windows

services:
  - docker

install:
  - docker pull jjmerelo/test-perl6
  - docker images

script:
  - docker run -t -v $TRAVIS_BUILD_DIR:/test --entrypoint=/bin/sh jjmerelo/test-perl6
    .travis/docker-entrypoint.sh
