name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
        raku-version:
          - 'latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install Dependencies
        run: |
          # Install ncurses
          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install -y libncurses5
          elif [ "$RUNNER_OS" == "macOS" ]; then
              brew update
              brew install ncurses
          else
              echo "$RUNNER_OS not supported"
              exit 1;
          fi
          # Install and test dependencies
          zef install --/test --test-depends --deps-only .
      - name: Install App::Prove6
        run: zef install --/test App::Prove6
      - name: Run Tests
        run: prove6 -l t
